name: lex_annotation
description: >
  Annotations for the lex_gen.
  This package does nothing without lex_gen.
version: 0.0.2
homepage: https://atprotodart.com
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/lex_annotation
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.3.0

topics:
  - atproto
  - bluesky
  - annotation

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
  import_sorter: ^4.6.0

import_sorter:
  emojis: true
